version: '3.8'
services:
    dashboard:
        container_name: dashboard-container
        build: ./client/location-dashboard
        ports:
            - '4200:80'
    
    car1:
        build: ./servers/server1
        ports: 
            - '1234:1234'
        environment: ['PORT:1234']
    
    car2:
        build: ./servers/server2
        ports: 
            - '5678:5678'
        environment: ['PORT:5678']
                    
    car3:
        build: ./servers/server3
        ports: 
            - '3080:3080'
        environment: ['PORT:3080']